// Copyright (c) 2025 Beijing Volcano Engine Technology Co., Ltd. and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package observability

import (
	"context"
	"encoding/json"
	"strings"

	"github.com/volcengine/veadk-go/log"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/sdk/instrumentation"
	"go.opentelemetry.io/otel/sdk/trace"
	oteltrace "go.opentelemetry.io/otel/trace"
)

var (
	spanInvokeAgent = "invoke_agent"

	gcpVertexAgentLLMRequestName   = "gcp.vertex.agent.llm_request"
	gcpVertexAgentToolCallArgsName = "gcp.vertex.agent.tool_call_args"
	gcpVertexAgentEventID          = "gcp.vertex.agent.event_id"
	gcpVertexAgentToolResponseName = "gcp.vertex.agent.tool_response"
	gcpVertexAgentLLMResponseName  = "gcp.vertex.agent.llm_response"
	gcpVertexAgentInvocationID     = "gcp.vertex.agent.invocation_id"
	gcpVertexAgentSessionID        = "gcp.vertex.agent.session_id"

	ADKAttributeKeyMap = map[string]string{
		gcpVertexAgentLLMRequestName:   AttrInputValue,
		gcpVertexAgentLLMResponseName:  AttrOutputValue,
		gcpVertexAgentToolCallArgsName: AttrGenAIToolInput,
		gcpVertexAgentToolResponseName: AttrGenAIToolOutput,
		gcpVertexAgentInvocationID:     AttrGenAIInvocationId,
		gcpVertexAgentSessionID:        AttrGenAISessionId,
	}
)

// isMatch returns true if we should keep the span in the final output.
// At this point, we filter out "call_llm" span generated by ADK-go with scope name is "gcp.vertex.agent".
func isMatch(span trace.ReadOnlySpan) bool {
	if span.InstrumentationScope().Name == "gcp.vertex.agent" {
		name := span.Name()
		if name == "call_llm" {
			return false
		}
	}
	return true
}

// VeADKTranslatedExporter wraps a SpanExporter and remaps ADK attributes to standard fields.
type VeADKTranslatedExporter struct {
	trace.SpanExporter
}

func (e *VeADKTranslatedExporter) ExportSpans(ctx context.Context, spans []trace.ReadOnlySpan) error {
	translated := make([]trace.ReadOnlySpan, 0, len(spans))
	registry := GetRegistry()

	for _, s := range spans {
		if !isMatch(s) {
			continue
		}

		ts := &translatedSpan{ReadOnlySpan: s}
		translated = append(translated, ts)

		// 1. Logic stitching via ToolCallID
		toolCallID := ""
		for _, kv := range s.Attributes() {
			if string(kv.Key) == AttrGenAIToolCallID {
				toolCallID = kv.Value.AsString()
				break
			}
		}

		if toolCallID != "" {
			if veadkParentSC, ok := registry.GetVeadkParentContextByToolCallID(toolCallID); ok {
				// We found a match! Record this TraceID mapping to align other spans in the same trace (like merged spans)
				registry.RegisterTraceMapping(s.SpanContext().TraceID(), veadkParentSC.TraceID())
				log.Debug("Matched tool via ToolCallID, established TraceID mapping",
					"tool_call_id", toolCallID,
					"adk_trace_id", s.SpanContext().TraceID().String(),
					"veadk_trace_id", veadkParentSC.TraceID().String(),
				)
			}
		}

	}

	if len(translated) == 0 {
		return nil
	}

	return e.SpanExporter.ExportSpans(ctx, translated)
}

// translatedSpan wraps a ReadOnlySpan and intercepts calls to Attributes().
type translatedSpan struct {
	trace.ReadOnlySpan
}

func (p *translatedSpan) Attributes() []attribute.KeyValue {
	attrs := p.ReadOnlySpan.Attributes()
	newAttrs := make([]attribute.KeyValue, 0, len(attrs)+5) // Pre-allocate with some extra space

	// Track existing keys and tool-related fields
	existingKeys := make(map[string]bool)
	var toolName, toolDesc, toolArgs, toolCallID, toolResponse string

	// First pass: scan for existing keys and raw data
	for _, kv := range attrs {
		existingKeys[string(kv.Key)] = true
		key := string(kv.Key)

		// Collect raw data for reconstruction
		switch key {
		case AttrGenAIToolName:
			toolName = kv.Value.AsString()
		case AttrGenAIToolDescription: // Note: ADK uses gen_ai.tool.description
			toolDesc = kv.Value.AsString()
		case gcpVertexAgentToolCallArgsName:
			toolArgs = kv.Value.AsString()
		case AttrGenAIToolCallID:
			toolCallID = kv.Value.AsString()
		case gcpVertexAgentToolResponseName:
			toolResponse = kv.Value.AsString()
		}
	}

	newAttrs = p.processAttributes(attrs, existingKeys)

	// Dynamic Reconstruction: Tool Input/Output from raw attributes
	if toolArgs != "" && toolName != "" {
		if inputAttrs := p.reconstructToolInput(toolName, toolDesc, toolArgs); inputAttrs != nil {
			newAttrs = append(newAttrs, inputAttrs...)
		}
	}

	if toolResponse != "" && toolCallID != "" {
		if outputAttrs := p.reconstructToolOutput(toolName, toolCallID, toolResponse); outputAttrs != nil {
			newAttrs = append(newAttrs, outputAttrs...)
		}
	}

	return newAttrs
}

func (p *translatedSpan) processAttributes(attrs []attribute.KeyValue, existingKeys map[string]bool) []attribute.KeyValue {
	newAttrs := make([]attribute.KeyValue, 0, len(attrs))
	for _, kv := range attrs {
		key := string(kv.Key)

		// 1. Map ADK internal attributes if not already present in standard form
		if strings.HasPrefix(key, "gcp.vertex.agent.") {
			targetKey, ok := ADKAttributeKeyMap[key]
			if ok {
				// Skip if we are going to reconstruct this field
				if targetKey == AttrGenAIToolInput || targetKey == AttrGenAIToolOutput {
					continue
				}

				// Only add mapped key if the target key doesn't already exist in the span
				if !existingKeys[targetKey] {
					newAttrs = append(newAttrs, attribute.KeyValue{Key: attribute.Key(targetKey), Value: kv.Value})
				}
			}
			continue
		}

		// 2. Patch gen_ai.system if needed
		if key == AttrGenAISystem && kv.Value.AsString() == "gcp.vertex.agent" {
			kv = attribute.String(AttrGenAISystem, "volcengine")
		}

		newAttrs = append(newAttrs, kv)
	}
	return newAttrs
}

func (p *translatedSpan) reconstructToolInput(toolName, toolDesc, toolArgs string) []attribute.KeyValue {
	var paramsMap map[string]any
	if err := json.Unmarshal([]byte(toolArgs), &paramsMap); err == nil {
		inputData := map[string]any{
			"name":        toolName,
			"description": toolDesc,
			"parameters":  paramsMap,
		}
		if inputJSON, err := json.Marshal(inputData); err == nil {
			val := string(inputJSON)
			return []attribute.KeyValue{
				attribute.String(AttrGenAIToolInput, val),
				attribute.String(AttrCozeloopInput, val),
				attribute.String(AttrGenAIInput, val),
			}
		}
	}
	return nil
}

func (p *translatedSpan) reconstructToolOutput(toolName, toolCallID, toolResponse string) []attribute.KeyValue {
	var responseMap map[string]any
	// ADK serializes response as map, unmarshal it first
	if err := json.Unmarshal([]byte(toolResponse), &responseMap); err == nil {
		outputData := map[string]any{
			"id":       toolCallID,
			"name":     toolName,
			"response": responseMap,
		}
		if outputJSON, err := json.Marshal(outputData); err == nil {
			val := string(outputJSON)
			return []attribute.KeyValue{
				attribute.String(AttrGenAIToolOutput, val),
				attribute.String(AttrCozeloopOutput, val),
				attribute.String(AttrGenAIOutput, val),
			}
		}
	}
	return nil
}

func (p *translatedSpan) SpanContext() oteltrace.SpanContext {
	sc := p.ReadOnlySpan.SpanContext()
	registry := GetRegistry()

	toolCallID := ""
	for _, kv := range p.ReadOnlySpan.Attributes() {
		if string(kv.Key) == AttrGenAIToolCallID {
			toolCallID = kv.Value.AsString()
			break
		}
	}

	if veadkParentSC, ok := registry.GetVeadkParentContextByToolCallID(toolCallID); ok {
		return oteltrace.NewSpanContext(oteltrace.SpanContextConfig{
			TraceID:    veadkParentSC.TraceID(),
			SpanID:     sc.SpanID(),
			TraceFlags: sc.TraceFlags(),
			TraceState: sc.TraceState(),
			Remote:     sc.IsRemote(),
		})
	}

	// 2. Try global TraceID mapping (for spans in the same trace without their own tool_call_id)
	if veadkParentSC, ok := registry.GetVeadkTraceID(sc.TraceID()); ok {
		return oteltrace.NewSpanContext(oteltrace.SpanContextConfig{
			TraceID:    veadkParentSC,
			SpanID:     sc.SpanID(),
			TraceFlags: sc.TraceFlags(),
			TraceState: sc.TraceState(),
			Remote:     sc.IsRemote(),
		})
	}

	// 3. Fallback to Tool SpanID mapping
	if veadkParentSC, ok := registry.GetVeadkSpanContext(sc.SpanID()); ok {
		return oteltrace.NewSpanContext(oteltrace.SpanContextConfig{
			TraceID:    veadkParentSC.TraceID(),
			SpanID:     sc.SpanID(),
			TraceFlags: sc.TraceFlags(),
			TraceState: sc.TraceState(),
			Remote:     sc.IsRemote(),
		})
	}

	return sc
}

func (p *translatedSpan) Parent() oteltrace.SpanContext {
	parent := p.ReadOnlySpan.Parent()
	sc := p.ReadOnlySpan.SpanContext()
	registry := GetRegistry()

	// 1. Precise Re-parenting based on internal ParentID mapping
	if parent.IsValid() {
		if veadkSC, ok := registry.GetVeadkSpanContext(parent.SpanID()); ok {
			return veadkSC
		}
	}

	// 2. Try ToolCallID mapping (for tool spans that lost parent context)
	toolCallID := ""
	for _, kv := range p.ReadOnlySpan.Attributes() {
		if string(kv.Key) == AttrGenAIToolCallID {
			toolCallID = kv.Value.AsString()
			break
		}
	}

	if manualParentSC, ok := registry.GetVeadkParentContextByToolCallID(toolCallID); ok {
		return manualParentSC
	}

	// 3. Fallback: Re-parent root spans if we have a direct mapping for this span ID.
	if !parent.IsValid() {
		if manualSC, ok := registry.GetVeadkSpanContext(sc.SpanID()); ok {
			return manualSC
		}
	}

	return parent
}

func (p *translatedSpan) InstrumentationScope() instrumentation.Scope {
	scope := p.ReadOnlySpan.InstrumentationScope()
	// github.com/volcengine/veadk-go is the InstrumentationName defined in observability/constant.go
	if scope.Name == "gcp.vertex.agent" || scope.Name == "veadk" || scope.Name == "github.com/volcengine/veadk-go" {
		scope.Name = "openinference.instrumentation.veadk"
	}
	scope.Version = Version
	return scope
}

func (p *translatedSpan) InstrumentationLibrary() instrumentation.Scope {
	return p.InstrumentationScope()
}
