package common

// DATABASE env key
const (
	//DATABASE_POSTGRESQL
	DATABASE_POSTGRESQL_USER         = "DATABASE_POSTGRESQL_USER"
	DATABASE_POSTGRESQL_PASSWORD     = "DATABASE_POSTGRESQL_PASSWORD"
	DATABASE_POSTGRESQL_HOST         = "DATABASE_POSTGRESQL_HOST"
	DATABASE_POSTGRESQL_PORT         = "DATABASE_POSTGRESQL_PORT"
	DATABASE_POSTGRESQL_DATABASE     = "DATABASE_POSTGRESQL_DATABASE"
	DATABASE_POSTGRESQL_DBURL        = "DATABASE_POSTGRESQL_DBURL"
	DATABASE_POSTGRESQL_GORMLOGLEVEL = "DATABASE_POSTGRESQL_GORMLOGLEVEL"
)

// Model env key
const (
	// Agent
	MODEL_AGENT_NAME     = "MODEL_AGENT_NAME"
	MODEL_AGENT_PROVIDER = "MODEL_AGENT_PROVIDER"
	MODEL_AGENT_API_BASE = "MODEL_AGENT_API_BASE"
	MODEL_AGENT_API_KEY  = "MODEL_AGENT_API_KEY"

	// Image
	MODEL_IMAGE_NAME     = "MODEL_IMAGE_NAME"
	MODEL_IMAGE_API_BASE = "MODEL_IMAGE_API_BASE"
	MODEL_IMAGE_API_KEY  = "MODEL_IMAGE_API_KEY"

	// Video
	MODEL_VIDEO_NAME     = "MODEL_VIDEO_NAME"
	MODEL_VIDEO_API_BASE = "MODEL_VIDEO_API_BASE"
	MODEL_VIDEO_API_KEY  = "MODEL_VIDEO_API_KEY"
)

// Embedding
const (
	MODEL_EMBEDDING_NAME     = "MODEL_EMBEDDING_NAME"
	MODEL_EMBEDDING_DIM      = "MODEL_EMBEDDING_DIM"
	MODEL_EMBEDDING_API_BASE = "MODEL_EMBEDDING_API_BASE"
	MODEL_EMBEDDING_API_KEY  = "MODEL_EMBEDDING_API_KEY"
)

// Logging env key
const (
	LOGGING_LEVEL = "LOGGING_LEVEL"
)

const (
	VOLCENGINE_ACCESS_KEY = "VOLCENGINE_ACCESS_KEY"
	VOLCENGINE_SECRET_KEY = "VOLCENGINE_SECRET_KEY"
)

// VIKING KNOWLEDGE BASE
const (
	DATABASE_VIKING_PROJECT = "DATABASE_VIKING_PROJECT"
	DATABASE_VIKING_REGION  = "DATABASE_VIKING_REGION"
)

// TOS
const (
	DATABASE_TOS_ENDPOINT = "DATABASE_TOS_ENDPOINT"
	DATABASE_TOS_REGION   = "DATABASE_TOS_REGION"
	DATABASE_TOS_BUCKET   = "DATABASE_TOS_BUCKET"
)

// AGENTKIT TOOL
const (
	AGENTKIT_TOOL_ID           = "AGENTKIT_TOOL_ID"
	AGENTKIT_TOOL_REGION       = "AGENTKIT_TOOL_REGION"
	AGENTKIT_TOOL_SERVICE_CODE = "AGENTKIT_TOOL_SERVICE_CODE"
	AGENTKIT_TOOL_HOST         = "AGENTKIT_TOOL_HOST"
)

// MCP ROUTER
const (
	TOOL_MCP_ROUTER_URL     = "TOOL_MCP_ROUTER_URL"
	TOOL_MCP_ROUTER_API_KEY = "TOOL_MCP_ROUTER_API_KEY"
)

// Mem0
const (
	DATABASE_MEM0_BASE_URL = "DATABASE_MEM0_BASE_URL"
	DATABASE_MEM0_API_KEY  = "DATABASE_MEM0_API_KEY"
	DATABASE_MEM0_REGION   = "DATABASE_MEM0_REGION"
)

// Prompt pilot
const (
	AGENTPILOT_API_URL      = "AGENTPILOT_API_URL"
	AGENTPILOT_API_KEY      = "AGENTPILOT_API_KEY"
	AGENTPILOT_WORKSPACE_ID = "AGENTPILOT_WORKSPACE_ID"
)

// LLM Shield
const (
	TOOL_LLM_SHIELD_URL     = "TOOL_LLM_SHIELD_URL"
	TOOL_LLM_SHIELD_REGION  = "TOOL_LLM_SHIELD_REGION"
	TOOL_LLM_SHIELD_APP_ID  = "TOOL_LLM_SHIELD_APP_ID"
	TOOL_LLM_SHIELD_API_KEY = "TOOL_LLM_SHIELD_API_KEY"
)

// coze loop
const (
	COZELOOP_WORKSPACE_ID = "COZELOOP_WORKSPACE_ID"
	COZELOOP_API_TOKEN    = "COZELOOP_API_TOKEN"
)
