package common

// DATABASE env key
const (
	DATABASE_SHORT_TERM_MEMORY_BACKEND = "DATABASE_SHORT_TERM_MEMORY_BACKEND"

	//DATABASE_POSTGRESQL
	DATABASE_POSTGRESQL_USERNAME     = "DATABASE_POSTGRESQL_USERNAME"
	DATABASE_POSTGRESQL_PASSWORD     = "DATABASE_POSTGRESQL_PASSWORD"
	DATABASE_POSTGRESQL_HOST         = "DATABASE_POSTGRESQL_HOST"
	DATABASE_POSTGRESQL_PORT         = "DATABASE_POSTGRESQL_PORT"
	DATABASE_POSTGRESQL_SCHEMA       = "DATABASE_POSTGRESQL_SCHEMA"
	DATABASE_POSTGRESQL_DBURL        = "DATABASE_POSTGRESQL_DBURL"
	DATABASE_POSTGRESQL_GORMLOGLEVEL = "DATABASE_POSTGRESQL_GORMLOGLEVEL"
)

// Model env key
const (
	MODEL_AGENT_NAME     = "MODEL_AGENT_NAME"
	MODEL_AGENT_PROVIDER = "MODEL_AGENT_PROVIDER"
	MODEL_AGENT_API_BASE = "MODEL_AGENT_API_BASE"
	MODEL_AGENT_API_KEY  = "MODEL_AGENT_API_KEY"
)

// Logging env key
const (
	LOGGING_LEVEL = "LOGGING_LEVEL"
)

const VEFAAS_IAM_CRIDENTIAL_PATH = "/var/run/secrets/iam/credential"

const (
	VOLCENGINE_ACCESS_KEY = "VOLCENGINE_ACCESS_KEY"
	VOLCENGINE_SECRET_KEY = "VOLCENGINE_SECRET_KEY"
)

const DEFAULT_LLMAGENT_NAME = "veLLMAgent"
